AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  ApiName:
    Type: String
  ExtractFaceInImagesArn:
    Type: String
  
Resources:
  APIGatewayREST:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Ref ApiName

  ExtractFaceInImagesResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref APIGatewayREST
      ParentId: !GetAtt 
        - APIGatewayREST
        - RootResourceId
      PathPart: !Ref ExtractFaceInImagesArn
    DependsOn: APIGatewayREST

  ExtractFaceInImagesMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref APIGatewayREST
      ResourceId: !Ref ExtractFaceInImagesResource
      HttpMethod: POST
      AuthorizationType: NONE
      MethodResponses:
        - StatusCode: 200
      Integration:
        Type: AWS
        IntegrationResponses:
          - StatusCode: 200
        IntegrationHttpMethod: POST
        Uri: !Sub 
          - >-
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFuncNameArn}/invocations
          - LambdaFuncNameArn: !Ref ExtractFaceInImagesArn
    DependsOn:
      - ExtractFaceInImagesResource
  
  ExtractFaceInImagesDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref APIGatewayREST
    DependsOn:
      - ExtractFaceInImagesMethod
  
  ExtractFaceInImagesPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ExtractFaceInImagesArn
      Principal: apigateway.amazonaws.com
    DependsOn:
      - ExtractFaceInImagesDeployment
