AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  BucketName:
    Type: String
  RuleID:
    Type: String
  SearchPrefix:
    Type: String

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref BucketName
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
            AllowedOrigins:
              - '*'
            ExposedHeaders:
              - Date
            MaxAge: 3600
      LifecycleConfiguration:
        Rules:
          - Id: !Ref RuleID
            Prefix: !Ref SearchPrefix
            Status: Enabled
            ExpirationInDays: 1
