AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  S3ImageBucket:
    Type: String
  RuleID:
    Type: String
  SearchPrefix:
    Type: String

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref S3ImageBucket
      LifecycleConfiguration:
        Rules:
          - Id: !Ref RuleID
            Prefix: !Ref SearchPrefix
            Status: Enabled
            ExpirationInDays: 1